title: "Uncertainty @ PowerUp 2026"
masthead_title: "Planning Under Uncertainty"
subtitle: "PowerUp 2026"
logo: "/favicon.svg"
description: "Energy Infrastructure Planning Under Uncertainty @ PowerUp 2026"
url: "https://pu26-uncertainty.github.io"
baseurl: ""
repository: "pu26-uncertainty/pu26-uncertainty.github.io"

favicon: "/favicon.ico"

anchor_links: false

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "air"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

include:
  - _pages

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

navigation:
  - title: "Overview"
    url: /overview/
  - title: "Materials"
    url: /materials/
  - title: "Speaker Bios"
    url: /speaker-bios/
  - title: "Organizer Bios"
    url: /organizer-bios/
  - title: "Agenda"
    url: /agenda/
  - title: "FAQs"
    url: /faqs/
